### ISSUE TITLE
TypeError: Cannot read property 'rawAttributes' of undefined

### ISSUE THREAD

**Issue by maynir** [jsamchineme/graphql-sequelize-query-loader#55]
I have a sequelize model name `Program`. In the typeDef of program there is now field `audience_segments` of type [AudienceSegment]. This `AudienceSegment` is a Mongoose model. So when I query to get all my programs and specify the audience_segments field i get this error because AudienceSegment is not a  sequelize model:
```
TypeError: Cannot read property 'rawAttributes' of undefined
    at Object.getSelectedAttributes (/app/node_modules/graphql-sequelize-query-loader/lib/queryLoader.js:192:53)
    at /app/node_modules/graphql-sequelize-query-loader/lib/queryLoader.js:126:45
    at Array.forEach (<anonymous>)
    at Object.prepareIncludes (/app/node_modules/graphql-sequelize-query-loader/lib/queryLoader.js:121:33)
    at Object.getSelectedIncludes (/app/node_modules/graphql-sequelize-query-loader/lib/queryLoader.js:175:29)
    at Object.getFindOptions (/app/node_modules/graphql-sequelize-query-loader/lib/queryLoader.js:96:36)
    at programs (file:///app/src/resolvers/Programs.js:6:40)
    at /app/node_modules/graphql-middleware/dist/applicator.js:19:114
    at middleware (/app/node_modules/graphql-shield/dist/generator.js:30:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24)
    at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24)
    at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24)
    at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24)
    at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24)
    at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24)
    at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24)
```

It fails when I call `queryLoader.getFindOptions({ model: models.programs, info: info })` in my programs resolver. 
How can I combine sequelize with mongoose so it will work?
Thanks.

**Comment by maynir** [comment]
@jsamchineme ?

**Comment by nicoabie** [comment]
@maynir we created a fork of this library because it appears to be discontinued and we are maintaining it here https://github.com/ReMatter/graphql-sequelize-query-loader

can you try to replicate and let me know?
